### ISSUE TITLE
record_store does not handle edits with multiple entries with the Dynect provider

### ISSUE THREAD

**Issue by charlescng** [Shopify/record_store#39]
Looks to have the same underlying problem as https://github.com/Shopify/record_store/issues/27.

Given the scenario where we have two existing TXT entries for the same FQDN:
```
www.example.com TXT foo
www.example.com TXT bar
```
We want to update the `bar` entry to `hello`. 

The existing code does not change the correct entry to `hello` with the Dynect entries. In fact it wants to delete the `foo` entry and update the `bar` entry to `hello`.

I suspect this is also a problem for other record types where there can be multiple entries which as A and AAAA.

The problem does not exist with DNSimple which is supported by Fog::DNS (without the need for another plugin).

**Comment by charlescng** [comment]
The test case isn't quite right. I'll edit it.

**Comment by charlescng** [comment]
The bug is actually somewhere else. I'll have to dig a bit deeper.

**Comment by sbfaulkner** [comment]
re-opened... the bug is (was?) in record_store... and the way it invokes fog-dynect
