### ISSUE TITLE
SPF Record Refactor

### ISSUE THREAD

**Issue by es** [Shopify/record_store#42]
SPF records are really just TXT records underneath with specific content. Our code should reflect that by having `Record::SPF` inherit from `Record::TXT`.

**Comment by es** [comment]
cc @sbfaulkner this would be a good onboarding to Record Store task

**Comment by sbfaulkner** [comment]
is there an actual bug here? or is it a new feature? or a cleanup chore?

**Comment by sbfaulkner** [comment]
I guess mostly just a refactor eliminating duplicate code, but probably fixes escaping issues for SPF records

**Comment by es** [comment]
Not an actual bug. Bad tag names 😛
